### ISSUE TITLE
users not receiving words after adding a level

### ISSUE THREAD

**Issue by rooom13** [rooom13/dailyWord-bot#18]
This exceptions is thrown:

`An exception occured in callback_chrono_send_top_tweets:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'level'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/daily_word_bot/app.py", line 288, in send_word
    word_data = self.word_bank.get_random(levels, exclude=exclude)
  File "/daily_word_bot/word_bank.py", line 57, in get_random
    df_candidates = self.df.loc[(~self.df.index.isin(exclude)) & ((self.df['level'].isin(levels)) | (self.df['level'] == ''))]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in getitem
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'level'`

**Comment by rooom13** [comment]
This line -> https://github.com/rooom13/dailyWord-bot/blob/0aedb1c3b4819a4fe0ee9d9d191dcc3353e3ea62/daily_word_bot/word_bank.py#L45

needs to be replaced by `df = pd.DataFrame(data, columns=header).set_index("word_id")`, so no columns are filtered out
